export const Strings = {
  homeScreen: {
    hello: "Hello!",
    title: "Home",
    screenName: "HomeScreen",
    fabAdd: "Adicionar",
    fabLogin: "Login",
    searchPlaceholder: "Pesquise uma obra, autor ou coleção",
    searchResultText: "Resultados de busca para: ",
    collections: "Coleções",
    emptyList: "Clique no + para adicionar um livro",
  },
  configsScreen: {
    title: "Configurações",
    screenName: "ConfigsScreen",
    alarmTitle: "Alarme",
    alarmDescription:
      "Se ativado, você receberá uma notificação amigável para ler todos os dias!",
    pickTime: "Definir horário",
    darkMode: "Modo escuro",
    timePickerLabel: "Escolha um horário",
    timePickerCancelLabel: "Cancelar",
    account: "Conta",
    logOut: 'Log out',
    deleteAccount: 'Apagar conta'
  },
  loginScreen: {
    screenName: "LoginScreen",
    title: "Login",
    password: 'Senha',
    visitor: 'Criar nova conta',
  },
  signUpScreen:{
    screenName: 'SignUpScreen',
    title: 'Nova conta',
    emailPlaceholder: 'Insira seu email',
    passwordPlaceholder: 'Crie uma senha',
    button: 'Criar nova conta'

  },
  aboutScreen: {
    screenName: "AboutScreen",
    title: "Sobre o app",
    appName: "Biblioteca da Camila",
    appVersion: "Versão: MVP",
    githubTitle: "GitHub",
    githubDesc: "Veja o código do projeto",
    instagramTitle: "Instagram da Camila",
    instagramDesc: "Eu posto desenhos lá",
    complaintsTitle: "Departamento de reclamações",
    complaintsDesc: "Envie seu feedback",
  },
  cameraScreen: {
    screenName: "CameraScreen",
    title: "Leitura de ISBN",
    goBack: "Voltar",
    flash: "Flash",
    permissionsTitle: "Permissões",
    permissionsDescription:
      "Precisamos da sua permissão para usar a câmera. Ela funcionará como leitor de código de barras.",
    permissionsRequest: "Solicitar",
  },
  metadataScreen: {
    screenName: "MetadataScreen",
    titleNewBook: "Cadastrar",
    titleEditing: "Editar",
    metadataTitle: "Metadados",
    bookTitle: "Título da obra",
    bookTitleHelper: "Só o título, sem adicionais. Campo obrigatório",
    collectionTitle: "Título da série",
    volumeTitleHelper:
      "Insira 1 em casos de livro único. Obrigatório.",
    collectionTitleHelper:
      "Insira o nome da obra em casos de livro único. Obrigatório.",
    author: "Autor",
    authorHelper:
      "Escolha uma grafia e use só ela para não atrapalhar o filtro",
    volume: "Número do volume",
    volumeHelper: "Somente números",
    isbn: "ISBN",
    isbnHelper: "Pode ser 10 ou 13 dígitos. Campo não editável.",
    publisher: "Editora",
    year: "Ano de publicação",
    synopsis: "Sinopse",
    noSynopsis: "Não encontrei uma sinopse",
    noSynopsisReally: "Sem sinopse, sem texto",
    readingStatus: "Status",
    unread: "Não lido",
    read: "Lido",
    bookKind: "Tipo",
    manga: "Mangá",
    book: "Livro",
    comics: "HQ",
    where: "Onde está a coleção",
    mothersHome: "Casa de mãe",
    myHome: "Minha casa",
    collectionStatus: "Status da coleção",
    collectionComplete: "Coleção completa",
    collectionIncomplete: "Coleção incompleta",
    coverArt: "Capa",
    uploadCoverCTA: "Upload da capa",
    opinionTitle: "Opinião",
    rating: "Avaliação",
    review: "Resenha",
    noReview: "Decidi não escrever uma resenha",
    noReviewReally: "Sem resenha, sem texto",
    manualScrapingTitle: "Scraping manual",
    manualScrapingDescription:
      "Use o ISBN Search para pegar arquivos e dados que o scan automático não pegou.",
    isbnSearch: "ISBN search",
    save: "Salvar",
    modalOk: "Voltar assim mesmo",
    modalCancel: "Ficar na tela",
    modalTitle: "Sair?",
    modalDescription:
      "Tem certeza que quer voltar? Você vai perder os dados não salvos!",
  },
  bookScreen: {
    title: "Detalhes",
    screenName: "BookScreen",
    volume: "Volume",
    back: "Voltar",
    delete: "Excluir assim mesmo",
    deleteModalTitle: "Exclusão de Livro",
    deleteModalDescription:
      "Tem certeza que quer apagar o livro? Não tem como recuperar depois!",
  },
};

export default Strings;
